import {
  Injectable,
  Logger,
  InternalServerErrorException,
} from '@nestjs/common';
import * as puppeteer from 'puppeteer';

@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);

  async generatePdfFromUrl(url: string, token?: string): Promise<Buffer> {
    this.logger.log(`Launching Puppeteer to generate PDF for: ${url}`);

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    try {
      const page = await browser.newPage();

      if (token) {
        await page.evaluateOnNewDocument((jwt) => {
          localStorage.setItem('pos_token', jwt);
        }, token);

        const parsedUrl = new URL(url);
        await page.setCookie({
          name: 'pos_token',
          value: token,
          domain: parsedUrl.hostname,
          path: '/',
        });
      }

      await page.goto(url, { waitUntil: 'networkidle0', timeout: 30000 });

      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        displayHeaderFooter: true,
        headerTemplate: '<div></div>',
        footerTemplate: `
          <div style="font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif; font-size: 8px; color: #64748b; width: 100%; display: flex; justify-content: space-between; padding: 0 20mm; box-sizing: border-box;">
            <span>Generated by POS System</span>
            <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
          </div>
        `,
        margin: {
          top: '0mm',
          bottom: '20mm',
          left: '0mm',
          right: '0mm',
        },
      });

      return Buffer.from(pdfBuffer);
    } catch (error) {
      const errorStack = error instanceof Error ? error.stack : undefined;
      this.logger.error(`Failed to generate PDF from ${url}`, errorStack);
      throw new InternalServerErrorException('Could not generate PDF document');
    } finally {
      await browser.close();
    }
  }
}
